### ISSUE TITLE
Wrap lines

### ISSUE THREAD

**Issue by paldepind** [tchajed/iris-simp-lang#1]
Hi 🙂. I'm currently instantiating Iris with a language and this repository is super useful. Thanks a lot for creating it.

Some of the lines for the comments are very long ([like this one](https://github.com/tchajed/iris-simp-lang/blob/016d2376be4c8188607e0de174c56c306a244825/src/adequacy.v#L14)). This makes things bit hard to read when browsing the repository through GitHub or in an editor that doesn't break long lines.

Would you be open to a PR that wraps all comments at 80 or 70 characters? Or alternatively, with one sentence per line (instead of one paragraph per line as now).

Note, [some lines](https://github.com/tchajed/iris-simp-lang/blob/016d2376be4c8188607e0de174c56c306a244825/src/heap_ra.v#L19) are already hard-wrapped.

**Comment by tchajed** [comment]
Thanks, I'm glad it was useful!

I'd be happy to take a PR that wraps comments to 80 characters if you want to submit one.
